name: furniture_shop
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc_test: ^9.0.1
  cached_network_image: ^3.2.0
  cqrs: ^6.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_hooks: ^0.18.1
  flutter_rating_bar: ^4.0.0
  freezed: ^0.15.1+1
  freezed_annotation: ^0.15.0
  infinite_scroll_pagination: ^3.1.0
  json_annotation: ^4.1.0
  keyboard_dismisser: ^2.0.0
  logging: ^1.0.2
  login_client: ^2.0.3
  login_client_flutter: ^2.0.0
  mocktail: ^0.2.0
  provider: ^6.0.1
  wc_form_validators: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.2
  json_serializable: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  contracts_generator: ^0.2.3
  lint: ^1.7.2


flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

