FROM leancode.azurecr.io/dotnet:rootless-6.0

ARG APP_VERSION

ENV APP_VERSION=${APP_VERSION}

WORKDIR /app
COPY Docker.Directory.Build.props Directory.Build.props

WORKDIR /app/code/tests
SHELL ["/bin/bash", "-c"]
ENTRYPOINT dotnet restore && dotnet watch msbuild /t:RunTests
