FROM leancode.azurecr.io/dotnet:rootless-6.0

ARG APP_VERSION

ENV APP_VERSION=${APP_VERSION}

WORKDIR /app
COPY Docker.Directory.Build.props Directory.Build.props

WORKDIR /app/code/tests/FurnitureShop.IntegrationTests
SHELL ["/bin/bash", "-c"]
ENTRYPOINT source /app/code/dev/config/integration_tests.sh && \
    /app/code/dev/tools/watch_tests.sh
