# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Mobile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v2

      - name: Verify Changed Files
        uses: tj-actions/changed-files@v23
        id: changed-files
        with:
          files: |
            web/*

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"

      - name: Run Flutter Tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          flutter pub get
          flutter test
        
