name: furniture_shop
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc_test: ^9.0.1
  cached_network_image: ^3.2.0
  cqrs: ^6.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_hooks: ^0.18.1
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^5.0.2
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  infinite_scroll_pagination: ^3.1.0
  json_annotation: ^4.5.0
  keyboard_dismisser: ^2.0.0
  leancode_contracts: ^0.2.1
  logging: ^1.0.2
  login_client: ^2.0.3
  login_client_flutter: ^2.0.1
  mocktail: ^0.3.0
  provider: ^6.0.1
  wc_form_validators: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.5
  json_serializable: ^6.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  lint: ^1.7.2
  leancode_lint: ^1.0.1+1
  leancode_contracts_generator: ^0.5.0

flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
