name: furniture_shop
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  azblob: ^2.3.0
  bloc_test: ^9.0.1
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  cqrs: ^6.2.0
  equatable: ^2.0.3
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_hooks: ^0.18.1
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  infinite_scroll_pagination: 3.1.0
  json_annotation: ^4.6.0
  keyboard_dismisser: ^2.0.0
  leancode_contracts: ^0.2.1
  logging: ^1.0.2
  login_client: ^2.0.3
  login_client_flutter: ^2.0.1
  mocktail: ^0.3.0
  model_viewer_plus: ^1.3.0
  path: ^1.8.2
  provider: ^6.0.1
  wc_form_validators: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5

  leancode_contracts_generator: ^0.5.0
  leancode_lint: ^1.0.1+1
  lint: ^1.7.2

flutter_gen:
  output: lib/resources/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
